# Generated by Django 4.2 on 2023-08-26 19:32

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_themes_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
